/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibesRouteImport } from './routes/vibes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PodcastsSlugRouteImport } from './routes/podcasts.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVibesRouteImport } from './routes/admin.vibes'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminStudioRouteImport } from './routes/admin.studio'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPodcastsRouteImport } from './routes/admin.podcasts'
import { Route as AdminPlaysRouteImport } from './routes/admin.plays'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAutoCommentsRouteImport } from './routes/admin.auto-comments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminPodcastsIndexRouteImport } from './routes/admin.podcasts.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminPodcastsNewRouteImport } from './routes/admin.podcasts.new'
import { Route as AdminPodcastsIdRouteImport } from './routes/admin.podcasts.$id'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const VibesRoute = VibesRouteImport.update({
  id: '/vibes',
  path: '/vibes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PodcastsSlugRoute = PodcastsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminVibesRoute = AdminVibesRouteImport.update({
  id: '/vibes',
  path: '/vibes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodcastsRoute = AdminPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaysRoute = AdminPlaysRouteImport.update({
  id: '/plays',
  path: '/plays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutoCommentsRoute = AdminAutoCommentsRouteImport.update({
  id: '/auto-comments',
  path: '/auto-comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodcastsIndexRoute = AdminPodcastsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPodcastsRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminPodcastsNewRoute = AdminPodcastsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPodcastsRoute,
} as any)
const AdminPodcastsIdRoute = AdminPodcastsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPodcastsRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vibes': typeof VibesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auto-comments': typeof AdminAutoCommentsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/plays': typeof AdminPlaysRoute
  '/admin/podcasts': typeof AdminPodcastsRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vibes': typeof AdminVibesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/podcasts/$id': typeof AdminPodcastsIdRoute
  '/admin/podcasts/new': typeof AdminPodcastsNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/podcasts/': typeof AdminPodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vibes': typeof VibesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auto-comments': typeof AdminAutoCommentsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/plays': typeof AdminPlaysRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vibes': typeof AdminVibesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/podcasts/$id': typeof AdminPodcastsIdRoute
  '/admin/podcasts/new': typeof AdminPodcastsNewRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/podcasts': typeof AdminPodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/podcasts': typeof PodcastsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vibes': typeof VibesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auto-comments': typeof AdminAutoCommentsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/plays': typeof AdminPlaysRoute
  '/admin/podcasts': typeof AdminPodcastsRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vibes': typeof AdminVibesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/podcasts/$slug': typeof PodcastsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/podcasts/$id': typeof AdminPodcastsIdRoute
  '/admin/podcasts/new': typeof AdminPodcastsNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/podcasts/': typeof AdminPodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/history'
    | '/podcasts'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/vibes'
    | '/admin/analytics'
    | '/admin/auto-comments'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/homepage'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/plays'
    | '/admin/podcasts'
    | '/admin/seo'
    | '/admin/studio'
    | '/admin/subscribers'
    | '/admin/users'
    | '/admin/vibes'
    | '/blog/$slug'
    | '/news/$slug'
    | '/podcasts/$slug'
    | '/admin/'
    | '/news/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/podcasts/$id'
    | '/admin/podcasts/new'
    | '/admin/blog/'
    | '/admin/podcasts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/history'
    | '/podcasts'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/vibes'
    | '/admin/analytics'
    | '/admin/auto-comments'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/homepage'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/plays'
    | '/admin/seo'
    | '/admin/studio'
    | '/admin/subscribers'
    | '/admin/users'
    | '/admin/vibes'
    | '/blog/$slug'
    | '/news/$slug'
    | '/podcasts/$slug'
    | '/admin'
    | '/news'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/podcasts/$id'
    | '/admin/podcasts/new'
    | '/admin/blog'
    | '/admin/podcasts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/history'
    | '/podcasts'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/vibes'
    | '/admin/analytics'
    | '/admin/auto-comments'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/homepage'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/plays'
    | '/admin/podcasts'
    | '/admin/seo'
    | '/admin/studio'
    | '/admin/subscribers'
    | '/admin/users'
    | '/admin/vibes'
    | '/blog/$slug'
    | '/news/$slug'
    | '/podcasts/$slug'
    | '/admin/'
    | '/news/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/podcasts/$id'
    | '/admin/podcasts/new'
    | '/admin/blog/'
    | '/admin/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  PodcastsRoute: typeof PodcastsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VibesRoute: typeof VibesRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibes': {
      id: '/vibes'
      path: '/vibes'
      fullPath: '/vibes'
      preLoaderRoute: typeof VibesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/podcasts/$slug': {
      id: '/podcasts/$slug'
      path: '/$slug'
      fullPath: '/podcasts/$slug'
      preLoaderRoute: typeof PodcastsSlugRouteImport
      parentRoute: typeof PodcastsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/vibes': {
      id: '/admin/vibes'
      path: '/vibes'
      fullPath: '/admin/vibes'
      preLoaderRoute: typeof AdminVibesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studio': {
      id: '/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podcasts': {
      id: '/admin/podcasts'
      path: '/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AdminPodcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plays': {
      id: '/admin/plays'
      path: '/plays'
      fullPath: '/admin/plays'
      preLoaderRoute: typeof AdminPlaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auto-comments': {
      id: '/admin/auto-comments'
      path: '/auto-comments'
      fullPath: '/admin/auto-comments'
      preLoaderRoute: typeof AdminAutoCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podcasts/': {
      id: '/admin/podcasts/'
      path: '/'
      fullPath: '/admin/podcasts/'
      preLoaderRoute: typeof AdminPodcastsIndexRouteImport
      parentRoute: typeof AdminPodcastsRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/podcasts/new': {
      id: '/admin/podcasts/new'
      path: '/new'
      fullPath: '/admin/podcasts/new'
      preLoaderRoute: typeof AdminPodcastsNewRouteImport
      parentRoute: typeof AdminPodcastsRoute
    }
    '/admin/podcasts/$id': {
      id: '/admin/podcasts/$id'
      path: '/$id'
      fullPath: '/admin/podcasts/$id'
      preLoaderRoute: typeof AdminPodcastsIdRouteImport
      parentRoute: typeof AdminPodcastsRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminPodcastsRouteChildren {
  AdminPodcastsIdRoute: typeof AdminPodcastsIdRoute
  AdminPodcastsNewRoute: typeof AdminPodcastsNewRoute
  AdminPodcastsIndexRoute: typeof AdminPodcastsIndexRoute
}

const AdminPodcastsRouteChildren: AdminPodcastsRouteChildren = {
  AdminPodcastsIdRoute: AdminPodcastsIdRoute,
  AdminPodcastsNewRoute: AdminPodcastsNewRoute,
  AdminPodcastsIndexRoute: AdminPodcastsIndexRoute,
}

const AdminPodcastsRouteWithChildren = AdminPodcastsRoute._addFileChildren(
  AdminPodcastsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAutoCommentsRoute: typeof AdminAutoCommentsRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPlaysRoute: typeof AdminPlaysRoute
  AdminPodcastsRoute: typeof AdminPodcastsRouteWithChildren
  AdminSeoRoute: typeof AdminSeoRoute
  AdminStudioRoute: typeof AdminStudioRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVibesRoute: typeof AdminVibesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAutoCommentsRoute: AdminAutoCommentsRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPlaysRoute: AdminPlaysRoute,
  AdminPodcastsRoute: AdminPodcastsRouteWithChildren,
  AdminSeoRoute: AdminSeoRoute,
  AdminStudioRoute: AdminStudioRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVibesRoute: AdminVibesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PodcastsRouteChildren {
  PodcastsSlugRoute: typeof PodcastsSlugRoute
}

const PodcastsRouteChildren: PodcastsRouteChildren = {
  PodcastsSlugRoute: PodcastsSlugRoute,
}

const PodcastsRouteWithChildren = PodcastsRoute._addFileChildren(
  PodcastsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  PodcastsRoute: PodcastsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VibesRoute: VibesRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
